myshop/account/urls.py
from django.conf.urls import url


from myshop.account import views

urlpatterns = [
    url(r'^add_fav/$', views.add_fav, name='add-fav'),
    url(r'^fav_list/$', views.fav_list, name='fav-list'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
]

myshop/cart/urls.py
from django.conf.urls import url
from myshop.cart import views

urlpatterns = [
    url(r'^add_count/$', views.add_count, name='add-count'),
    url(r'^cart_detail/$', views.detail, name='cart-detail'),
    url(r'^add_cart/$', views.add_cart, name='add-cart'),

]

myshop/product/urls.py
from django.conf.urls import url


from myshop.product import views

urlpatterns = [
    url(r'^list/$', views.product_list, name='product-list'),
    url(r'^detail/(?P<product_id>\d+)/$', views.product_detail, name='product-detail'),
]

myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from myshop.product import views
from myshop.account import views as account_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.product_list, name='home'),
    url(r'^product/', include('myshop.product.urls', namespace='product')),
    url(r'^account/', include('myshop.account.urls', namespace='account')),
    url(r'^cart/', include('myshop.cart.urls', namespace='cart')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myshop/account/models.py
from django.db import models
from django.contrib.auth.models import User

# class UserProfile(models.Model):
#     user = models.OneToOneField(User)


class UserFavorite(models.Model):
    user = models.ForeignKey(User)
    fav_id = models.IntegerField(default=0)

myshop/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from myshop.product.models import Product


class Cart(models.Model):
    user = models.ForeignKey(User)
    product = models.ForeignKey(Product)
    count = models.IntegerField(default=1)

    def get_item_price(self):
        return self.product.price*self.count

myshop/product/models.py
from __future__ import unicode_literals

from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category)
    name = models.CharField(max_length=200)

    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    description = models.TextField(blank=True,null=True)

    status = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_first_image(self):
        self.productimage_set.first()

class ProductImage(models.Model):
    product = models.ForeignKey(Product, null=True, blank=True)
    image = models.ImageField(upload_to='product/%Y/%m', max_length=255)
    display_order = models.PositiveSmallIntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s : %s'%(self.product.name, self.display_order)

myshop/account/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        fields=['username', 'password']
        model = User

myshop/account/views.py
from django.shortcuts import render, HttpResponse, redirect
from myshop.account.models import UserFavorite
from myshop.product.models import Product
from myshop.account.forms import UserForm
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_user
from django.contrib.auth import logout as logout_user


def add_fav(request):
    user = request.user
    fav_id = request.POST.get('fav_id', 0)
    if fav_id:
        product = Product.objects.filter(id=fav_id)
        if UserFavorite.objects.filter(user=user, fav_id=fav_id).exists():
            UserFavorite.objects.filter(user=user, fav_id=fav_id).delete()
            return HttpResponse('取消收藏')
        else:
            UserFavorite.objects.create(user=user, fav_id=fav_id)
            return HttpResponse('已收藏')


def login(request):
    form = UserForm(request.POST)
    if form.is_valid():
        username = form.cleaned_data['username']
    user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
    if user:
        login_user(request, user)
        return redirect('/')

    return render(request, 'account/login.html', {
        'form': form,
    })

def logout(request):
    if request.user:
        logout_user(request)
        return redirect('/')

def fav_list(request):
    ufs = UserFavorite.objects.filter(user=request.user)
    uf_list = []
    for uf in ufs:
        uf_list.append(uf.fav_id)
    products = Product.objects.filter(id__in=uf_list)

    return render(request, 'account/fav_list.html', {
        'products': products,
    })

myshop/cart/views.py
from django.shortcuts import render, HttpResponse, redirect
from myshop.cart.models import *


def add_cart(request):
    product_id=request.POST.get('product_id')
    if request.user:
        Cart.objects.get_or_create(user=request.user, product_id=product_id)

def add_count(request):
    if request.POST.get('cart_id'):
        cart = Cart.objects.filter(id=request.POST.get('cart_id')).first()
        cart.count += 1
        cart.save()
        return HttpResponse('yes')

def detail(request):
    carts = Cart.objects.filter(user=request.user)
    price = 0
    for cart in carts:
        price = price + cart.get_item_price()
    return render(request, 'cart/cart-detail.html',{
        'carts': carts,
        'total_price': price,
    })

myshop/product/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404

from myshop.product.models import *
from myshop.account.models import *
from myshop.cart.models import *


def product_list(request):
    products = Product.objects.filter(status=True)
    carts = Cart.objects.filter(user=request.user)
    return render(request, 'product/list.html', {
        'products': products,
        'carts': carts,
    })


def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    carts = Cart.objects.filter(user=request.user)
    fav = False
    if request.user.is_authenticated():
        fav = UserFavorite.objects.filter(user=request.user, fav_id=product_id).exists()
    if product:
        return render(request, 'product/detail.html', {
            'product': product,
            'images': product.productimage_set.all(),
            'fav': fav,
            'carts': carts,
        })

templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% trans "My shop" %}{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
    <div style="width:1200px; margin-right:0;">
    {% if request.user.is_authenticated %}
        <div >
            {% with total_items=carts|length %}
                {% if total_items > 0 %}
                    {% trans "Your cart" %}:
                    <a >
                        {% blocktrans with total_items_plural=total_items|pluralize total_price=cart.get_total_price %}
                            {{ total_items }} item{{ total_items_plural }}, ${{ total_price }}
                        {% endblocktrans %}
                    </a>
                {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
        </div>
    {% else %}
    {% endif %}
    </div>

    <div  style="width:1200px; margin-left:0;" >
        {% if request.user.is_authenticated %}
            <a href="{% url 'account:fav-list' %}">{{ user.username }}</a>/<a href="{% url 'account:logout' %}">logout</a>
        {% else %}
            <a href="{% url 'account:login' %}">login</a>/<a>sign in</a>
        {% endif %}
    </div>

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <script src="{% static 'js/jquery-3.1.1.js' %}" type="text/javascript"></script>
</body>
</html>

templates/cart/cart-detail.html
{% load static %}
<!DOCTYPE html>
<br lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="{% static 'js/jquery-3.1.1.js' %}" type="text/javascript"></script>

</head>
<br>
    {% for cart in carts %}
        <br>
        {{ cart.product.name }}
        <a><button  type="button" value="{{ cart.id }}" >+</button></a>
        </br>
    {% endfor %}
    <br>{{ total_price }}</br>

    <script type="text/javascript">

        $("button").click(function add_count(){
                $.ajax({
                       url:"{% url 'cart:add-count' %}",
                       type: 'POST',
                       data: {"cart_id":this.value},
                       success: function(refresh){
                  location.reload();
                }
                    })
                })
    </script>
</body>
</html>

templates/product/detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}


{% block content %}
    <body>
        <div class="product-detail">
            <h1>商品详情</h1>
            {% for image in images %}
                <img src="{{ image.image.url }}" width="480px" height="270px">
            {% endfor %}
            <div>
                <h2>{{ product.name }}</h2>
                <p class="price">${{ product.price }}</p>
                <div>
                    <button class="btn-danger" type="button" onclick="javascript:add_cart()">加入购物车</button>
                </div>
                <div>
                    <button class="btn" type="button" onclick="javascript:add_fav()">{% if fav %}已收藏{% else %}收藏{% endif %}</button>
                </div>
                {{ product.description|linebreaks }}

            </div>　
        </div>
        <script type="text/javascript">
            function add_fav(){
                $.ajax({
                       url:"/account/add_fav/",
                       type: 'POST',
                       data: {"fav_id":{{product.id}}},
                       success: function(refresh){
                  location.reload();
                }
                    })
                }
            function add_cart(){
                $.ajax({
                       url:"{% url 'cart:add-cart' %}",
                       type: 'POST',
                       data: {"product_id":{{product.id}}},

                    })
                }
        </script>
    </body>
{% endblock %}

templates/product/list.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% block content %}
<body>
    <h1>商品列表</h1>
    <table>
        <thead>
            <tr>
                <th>image</th>
                <th>name</th>
                <th>price</th>
            </tr>
        </thead>

        <tbody>
            {% for product in products %}
                <tr>
                    <td>
                        <img src="{{ product.productimage_set.first.image.url }}" width="50px" height="40px">
                    </td>
                    <td>
                        <a href="{% url 'product:product-detail' product.id %}">{{ product.name }}</a>
                    </td>
                    <td>{{ product.price }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
{% endblock %}
</html>